### ISSUE TITLE
some question about your posts

### ISSUE THREAD

**Issue by cslvjt** [pHaeusler/codef-experiments#3]
Thank you for introduction about CoDeF. I have a question about your blog.

![image](https://github.com/pHaeusler/codef-experiments/assets/65208601/5bbf08f9-86d5-4af9-b915-16090882b5d6)
how to generate this image and Why do you generate images with so many artifacts? 
but I didn't generate it follow the original author code.
![image](https://github.com/pHaeusler/codef-experiments/assets/65208601/c3483635-7072-4772-9063-deb29396bad5)
This is my generation.
Thank you.

**Comment by pHaeusler** [comment]
You have a better reconstruction than mine, for sure! Its possible my simpler implementation isn't working as well as the original code, or perhaps batch processing is changing the optimization a bit. 

You should see these images saved under `results/deform_XXX.png` when you call `run.py`

**Comment by cslvjt** [comment]
Thank you for your reply. I think the problem of artifacts is caused by the lack of optical flow loss function during training.
